### ISSUE TITLE
Add @karllab41 latest Tensorflow Medium Blog

### ISSUE THREAD

**Issue by karllab41** [Lab41/mediumblog#1]
Would like to have `gather_nd` blog post by @karllab41 to be added to this for transfer into the inside.

**Comment by karllab41** [comment]
I've just added it. Pending review by @d-grossman to bring it to more eyes.

**Comment by d-grossman** [comment]
this is a fantastic use of hacktoberfest labels.  Get these things pulled, so more people can see them.
